version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: wp_mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: hachi
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    container_name: wp_web
    restart: always
    depends_on:
      - db
    ports:
      - "8005:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: hachi
      WORDPRESS_DB_PASSWORD: 123

volumes:
  db_data:
